Tactics\OpleidingsbudgetBundle\Entity\ExpenseRequest:
    type: entity
    repositoryClass: Tactics\OpleidingsbudgetBundle\Repository\ExpenseRequestRepository
    table: expenserequest
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY

    fields:
        amount:
            type: decimal
            precision: 6
            scale: 2
            nullable: false

        description:
            type: text
            length: 255
            nullable: false

        status:
            type: text
            length: 255
            nullable: false

        date_pending:
            type: date
            nullable: true

        date_approved:
            type: date
            nullable: true

        date_executed:
            type: date
            nullable: true

        user_id:
            type: integer
            nullable: false
    ManyToOne:
        user:
            targetEntity: User