Tactics\OpleidingsbudgetBundle\Entity\Transaction:
    type: entity
    repositoryClass: Tactics\OpleidingsbudgetBundle\Repository\TransactionRepository
    table: transaction
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY

    fields:
        amount:
            type: decimal
            precision: 6
            scale: 2
            nullable: false

        type:
            type: text
            length: 255
            nullable: false

        date:
            type: date
            nullable: true

    manyToOne:
        user:
            targetEntity: User
    oneToOne:
        expenserequest:
            targetEntity: ExpenseRequest