Tactics\OpleidingsbudgetBundle\Entity\User:
    type: entity
    table: user

    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY

    fields:
        first_name:
            type: text
            length: 255
            nullable: true

        name:
            type: text
            length: 255
            nullable: true
