home:
  pattern: /
  defaults: { _controller: TacticsOpleidingsbudgetBundle:User:index }

tactics_edit_user:
  pattern: /profile/edit/{username}
  defaults: { _controller: TacticsOpleidingsbudgetBundle:Profile:edit }