parameters:
#    tactics_opleidingsbudget.example.class: Tactics\OpleidingsbudgetBundle\Example

services:
#    tactics_opleidingsbudget.example:
#        class: %tactics_opleidingsbudget.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
