parameters:
#    tactics_opleidingsbudget.example.class: Tactics\OpleidingsbudgetBundle\Example
    transaction_converter.class: Tactics\OpleidingsbudgetBundle\Converter\XeTransactionConverter

services:
#    tactics_opleidingsbudget.example:
#        class: %tactics_opleidingsbudget.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    tactics_user.registration.form.type:
        class: Tactics\OpleidingsbudgetBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: registration }

    tactics_user.alter_users.form.type:
        class: Tactics\OpleidingsbudgetBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%, @security.context]
        tags:
            - { name: form.type, alias: alter_users }

    opleidingsbudget_mailer:
        class: Tactics\OpleidingsbudgetBundle\Mailer\OpleidingsbudgetMailer
        arguments: [@mailer]

    opleidingsbudget.type.money:
        class: Tactics\OpleidingsbudgetBundle\Form\Type\MoneyType
        tags:
            - { name: form.type, alias: value_money }

    tactics.twig.tactics_extension:
        class: Tactics\OpleidingsbudgetBundle\Twig\TacticsExtension
        tags:
            - { name: twig.extension }

    transaction.repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - Tactics\OpleidingsbudgetBundle\Entity\Transaction

    transaction.converter:
        class: "%transaction_converter.class%"

    transaction.service:
        class: Tactics\OpleidingsbudgetBundle\Service\TransactionService
        arguments: [@transaction.repository, @transaction.converter]

