parameters:
#    tactics_opleidingsbudget.example.class: Tactics\OpleidingsbudgetBundle\Example

services:
#    tactics_opleidingsbudget.example:
#        class: %tactics_opleidingsbudget.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    tactics_user.registration.form.type:
        class: Tactics\OpleidingsbudgetBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: registration }

    tactics_user.alter_users.form.type:
        class: Tactics\OpleidingsbudgetBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%, @security.context]
        tags:
            - { name: form.type, alias: alter_users }

    opleidingsbudget_mailer:
        class: Tactics\OpleidingsbudgetBundle\Mailer\OpleidingsbudgetMailer
        arguments: [@mailer]

    opleidingsbudget.type.money:
        class: Tactics\OpleidingsbudgetBundle\Form\Type\MoneyType
        tags:
            - { name: form.type, alias: value_money }
