security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login_firewall:
            pattern: ^/login$
            anonymous: true

        main:
            pattern: ^/
            form_login:
                provider:       fos_userbundle
                csrf_provider:  form.csrf_provider
#                login_path:     /login
#                use_forward:    true
#                check_path:     /login_check
#                failure_path:   null
                always_use_default_target_path: false
                default_target_path:  /roles
            logout:     true
            anonymous:  true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }

    role_hierarchy:
        EXECUTER:         USER
        APPROVER:         EXECUTOR

