expenserequest:
    pattern:  /
    defaults: { _controller: "TacticsOpleidingsbudgetBundle:ExpenseRequest:index" }

expenserequest_all:
    pattern: /all
    defaults: { _controller: "TacticsOpleidingsbudgetBundle:ExpenseRequest:all" }

expenserequest_show:
    pattern:  /{id}/show
    defaults: { _controller: "TacticsOpleidingsbudgetBundle:ExpenseRequest:show" }

expenserequest_new:
    pattern:  /new
    defaults: { _controller: "TacticsOpleidingsbudgetBundle:ExpenseRequest:new" }

expenserequest_create:
    pattern:  /create
    defaults: { _controller: "TacticsOpleidingsbudgetBundle:ExpenseRequest:create" }
    requirements: { _method: post }

expenserequest_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "TacticsOpleidingsbudgetBundle:ExpenseRequest:edit" }

expenserequest_update:
    pattern:  /{id}/update
    defaults: { _controller: "TacticsOpleidingsbudgetBundle:ExpenseRequest:update" }
    requirements: { _method: post|put }

expenserequest_update_pending:
    pattern:  /{id}/update
    defaults: { _controller: "TacticsOpleidingsbudgetBundle:ExpenseRequest:updatePending" }
    requirements: { _method: post|get|put }

expenserequest_update_executed:
    pattern:  /{id}/update
    defaults: { _controller: "TacticsOpleidingsbudgetBundle:ExpenseRequest:updateApproved" }
    requirements: { _method: post|get|put }

expenserequest_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "TacticsOpleidingsbudgetBundle:ExpenseRequest:delete" }
    requirements: { _method: post|get|delete }
