fos_user_registration_register:
    pattern:  /
    defaults: { _controller: "TacticsOpleidingsbudgetBundle:Registration:register" }

fos_user_registration_check_email:
    pattern:  /check-email
    defaults: { _controller: "TacticsOpleidingsbudgetBundle:Registration:checkEmail" }

fos_user_registration_confirm:
    pattern:  /confirm/{token}
    defaults: { _controller: "TacticsOpleidingsbudgetBundle:Registration:confirm" }

fos_user_registration_confirmed:
    pattern:  /confirmed
    defaults: { _controller: "TacticsOpleidingsbudgetBundle:Registration:confirmed" }