transaction:
    pattern:  /
    defaults: { _controller: "TacticsOpleidingsbudgetBundle:Transaction:index" }

transaction_all:
    pattern: /all
    defaults: { _controller: "TacticsOpleidingsbudgetBundle:Transaction:all" }

transaction_show:
    pattern:  /{id}/show
    defaults: { _controller: "TacticsOpleidingsbudgetBundle:Transaction:show" }

transaction_new:
    pattern:  /new/{userid}/{type}/{expenserequestid}
    defaults: { _controller: "TacticsOpleidingsbudgetBundle:Transaction:new", expenserequestid: 0 }

#transaction_create:
#    pattern:  /create
#    defaults: { _controller: "TacticsOpleidingsbudgetBundle:Transaction:create" }
#    requirements: { _method: post }

transaction_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "TacticsOpleidingsbudgetBundle:Transaction:edit" }

transaction_update:
    pattern:  /{id}/update
    defaults: { _controller: "TacticsOpleidingsbudgetBundle:Transaction:update" }
    requirements: { _method: post|put }

transaction_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "TacticsOpleidingsbudgetBundle:Transaction:delete" }
    requirements: { _method: post|delete }
