transaction:
    pattern:  /
    defaults: { _controller: "TacticsOpleidingsbudgetBundle:Transaction:index" }

transaction_show:
    pattern:  /{id}/show
    defaults: { _controller: "TacticsOpleidingsbudgetBundle:Transaction:show" }

transaction_new_budget:
    pattern:  /new/{usrid}/budget
    defaults: { _controller: "TacticsOpleidingsbudgetBundle:Transaction:newBudget" }

transaction_new_endofyear:
    pattern:  /new/{usrid}/endofyear
    defaults: { _controller: "TacticsOpleidingsbudgetBundle:Transaction:newEndofYear" }

transaction_create:
    pattern:  /create
    defaults: { _controller: "TacticsOpleidingsbudgetBundle:Transaction:create" }
    requirements: { _method: post }

transaction_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "TacticsOpleidingsbudgetBundle:Transaction:edit" }

transaction_update:
    pattern:  /{id}/update
    defaults: { _controller: "TacticsOpleidingsbudgetBundle:Transaction:update" }
    requirements: { _method: post|put }

transaction_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "TacticsOpleidingsbudgetBundle:Transaction:delete" }
    requirements: { _method: post|delete }
